#!/bin/bash
#For 10xv2 starvation data


/home/tchari/rmats_conda_env/bin/STAR-avx2 --twopassMode Basic --runThreadN 10  --soloType Droplet --soloCBwhitelist /home/tchari/clytia_alt_splice/metadata/neur_fed_1to4.txt --readFilesIn /data/tchari/fastqs/fs_1to4_R2.fastq.gz /data/tchari/fastqs/fs_1to4_R1.fastq.gz --soloFeatures GeneFull SJ Velocyto --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --outSAMtype BAM SortedByCoordinate --genomeDir /home/tchari/clytia_alt_splice/reference/STAR --sjdbGTFfile /home/tchari/clytia_alt_splice/reference/transcripts.fa.transdecoder.genome_geneAndTrans.gtf --outFileNamePrefix /data/tchari/rmats_out/rmats_fedstarv/neur_fs_1to4_bam --readFilesCommand zcat --soloBarcodeReadLength 0

/home/tchari/rmats_conda_env/bin/STAR-avx2 --twopassMode Basic --runThreadN 10  --soloType Droplet --soloCBwhitelist /home/tchari/clytia_alt_splice/metadata/neur_fed_5to8.txt --readFilesIn /data/tchari/fastqs/fs_5to8_R2.fastq.gz /data/tchari/fastqs/fs_5to8_R1.fastq.gz --soloFeatures GeneFull SJ Velocyto --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --outSAMtype BAM SortedByCoordinate --genomeDir /home/tchari/clytia_alt_splice/reference/STAR --sjdbGTFfile /home/tchari/clytia_alt_splice/reference/transcripts.fa.transdecoder.genome_geneAndTrans.gtf --outFileNamePrefix /data/tchari/rmats_out/rmats_fedstarv/neur_fs_5to8_bam --readFilesCommand zcat --soloBarcodeReadLength 0

/home/tchari/rmats_conda_env/bin/STAR-avx2 --twopassMode Basic --runThreadN 10  --soloType Droplet --soloCBwhitelist /home/tchari/clytia_alt_splice/metadata/neur_starv_1to4.txt --readFilesIn /data/tchari/fastqs/fs_1to4_R2.fastq.gz /data/tchari/fastqs/fs_1to4_R1.fastq.gz --soloFeatures GeneFull SJ Velocyto --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --outSAMtype BAM SortedByCoordinate --genomeDir /home/tchari/clytia_alt_splice/reference/STAR --sjdbGTFfile /home/tchari/clytia_alt_splice/reference/transcripts.fa.transdecoder.genome_geneAndTrans.gtf --outFileNamePrefix /data/tchari/rmats_out/rmats_fedstarv/neur_starv_1to4_bam --readFilesCommand zcat --soloBarcodeReadLength 0

/home/tchari/rmats_conda_env/bin/STAR-avx2 --twopassMode Basic --runThreadN 10  --soloType Droplet --soloCBwhitelist /home/tchari/clytia_alt_splice/metadata/neur_starv_5to8.txt --readFilesIn /data/tchari/fastqs/fs_5to8_R2.fastq.gz /data/tchari/fastqs/fs_5to8_R1.fastq.gz --soloFeatures GeneFull SJ Velocyto --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --outSAMtype BAM SortedByCoordinate --genomeDir /home/tchari/clytia_alt_splice/reference/STAR --sjdbGTFfile /home/tchari/clytia_alt_splice/reference/transcripts.fa.transdecoder.genome_geneAndTrans.gtf --outFileNamePrefix /data/tchari/rmats_out/rmats_fedstarv/neur_starv_5to8_bam --readFilesCommand zcat --soloBarcodeReadLength 0
